"""связал таблицу задач и пользователей

Revision ID: 188d2c08a9eb
Revises: 11222c4f4b83
Create Date: 2025-04-15 07:51:28.999453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '188d2c08a9eb'
down_revision: Union[str, None] = '11222c4f4b83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('created_by', sa.BigInteger(), nullable=False))
    op.create_foreign_key(None, 'tasks', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'created_by')
    # ### end Alembic commands ###
